notifications:
  hipchat:
    rooms:
      secure: MpvHe3jcw/L9yoQYwC3QU5HhEalxHAC88AXbA1UdWG/F3KSMhlZEoRQrU34C4schqE4Ivj93ffsN0u5LcOwjVRhhvA5s3sNP+1tNLnpN5IDDLhb6mGSP9J3erE8GDbIWMG6HizHnz8nKmPw0ugvMCEvxNTePfLmR9uD31zp4IEo=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.10
- 0.11
- 0.12
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- gulp --node-server --angular-mock-backend &
- sleep 3
script:
- gulp test
- npm run protractor
after_script:
- gulp send-stats-to-coveralls
before_deploy:
- gulp release --version-suffix=${TRAVIS_TAG:-$TRAVIS_COMMIT}
deploy:
  - provider: heroku
    api_key:
      secure: XeBcMSubQ+kDtk7B93iJy5HCvXTxp708hUtn9RfjKtNjOyTOha25xZ3lRnYqrhgAOlTY7kieu8QtI4KOZmiRy3U1NwIardvUU44I4f9Q4DDJRGGrPyd61WZwyuAiPWUrePGadZJW2kSuxRXyD3QNm8mBr2njcQp9ln9TpS/57S4=
    app:
      master: ushahidi-platform-master
      release: ushahidi-platform-release
    on:
      repo: ushahidi/platform-client
      branch:
        - master
        - release
  - provider: releases
    api_key:
      secure: Txqa+XwZOOdAaxRckHGXSCkT7GEUh4R6R0MtTu8otA1Vv2/W5qTICuFnaEzV/FVWrSzYbMwM+mAFHQ1L8SXOnAvbSFwnjaOjIvaEUESItkSITDXncTJItJatzMUXT0SjRTm4Jy6LQ0Pq0qXxfWD6DzsWxPVPsthprb+aEzS0/m8=
    file: build/*
    file_glob: true
    skip_cleanup: true
    on:
      repo: ushahidi/platform-client
      tags: true
      all_branches: true

